#! /bin/sh
PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

# resize p2 to remainder of /dev/mmcblk0
log_daemon_msg "Repartitioning /dev/mmcblk0..." &&
  printf "p\nd\n2\nn\np\n2\n\n\np\nw" | fdisk /dev/mmcblk0

# resize the / partition
if [ -b /dev/mmcblk0p2 ]; then
  log_daemon_msg "Resizing /..." &&
    resize2fs /dev/mmcblk0p2
fi

# mount /tmp as a tempfs
log_daemon_msg "Mounting /tmp using tempfs..." &&
  echo "tmpfs /tmp tmpfs noatime,nosuid,nodev,noexec,mode=1777,size=512M 0 0" >> /etc/fstab

# primary usb disk
if [ -b /dev/sda ]; then

  # small swap partition as sda1, rest as sda2
  printf "p\ng\nn\n1\n\n+4G\nn\n2\n\n\np\nw" | fdisk /dev/sda

  # make a swap fs on the swap partition
  log_daemon_msg "Formatting swap on /dev/sda1..." &&
    mkswap /dev/sda1

  # create an ext4 filesystem
  log_daemon_msg "Formatting ext4 on /dev/sda2..." &&
    mkfs.ext4 -F /dev/sda2

  # set up as perm fstab entry with low swappiness
  UUID=`blkid /dev/sda1 | awk '{print $2}' | sed 's/"//g'`
  log_daemon_msg "Adding swap to fstab..." &&
    echo 'vm.swappiness = 1' >> /etc/sysctl.conf &&
    echo "$UUID none swap defaults 0 0" >> /etc/fstab &&
    swapon /dev/sda1

  # mount at /var and move existing /var over
  UUID=`blkid /dev/sda2 | awk '{print $2}' | sed 's/"//g'`
  log_daemon_msg "Moving /var to /dev/sda2..." &&
    mv /var /var.old && mkdir /var &&
    echo "$UUID /var ext4 errors=remount-ro,noatime 0 2" >> /etc/fstab &&
    mount /dev/sda2 /var && cp -dpr /var.old/* /var

fi

# move to next stage
mv /media/boot/onboot-2 $0 &&
  sync &&
  reboot
