#! /bin/sh
PATH=/sbin:/usr/sbin:/bin:/usr/bin
VERSION="3.14.79"

. /lib/init/vars.sh
. /lib/lsb/init-functions

# check the kernel version is correct
if ! [[ `uname -r` =~ $VERSION ]]; then

  # Updating the kernel and calling `reboot` causes the ODroid nodes to not
  # come back up by themselves. They will require a manual power cycle.

  URL="https://s3-eu-west-1.amazonaws.com/daft.cluster/kernel/kernel-$VERSION.tar.gz"

  log_daemon_msg "Updating kernel..." &&
    curl -s $URL | tar xvzf - -C /usr/src &&
    cd /usr/src/kernel &&
    make modules_install &&
    cp -f arch/arm64/boot/Image /media/boot/ &&
    cp -f arch/arm64/boot/dts/meson64_odroidc2.dtb /media/boot/ &&
    cd /usr/src &&
    rm -rf /usr/src/kernel

  # cleanup
  rm $0 &&
    sync &&
    shutdown -h now

fi

