#! /bin/sh
PATH=/sbin:/usr/sbin:/bin:/usr/bin
export DEBIAN_FRONTEND="noninteractive"

. /lib/init/vars.sh
. /lib/lsb/init-functions

# blitz old /var
if [ -d /var.old ]; then
  log_daemon_msg "Removing /var.old..." &&
    rm -rf /var.old
fi

# ntp goes weird on systemd
log_daemon_msg "Reinstalling ntp..." &&
  apt-get update &&
  apt-get -y purge ntp &&
  apt-get -y install ntp

# all cluster nodes require the following packages
log_daemon_msg "Installing essential packages..." &&
  apt-get -y install lxc aufs-tools cgroup-lite apparmor docker.io \
  curl git-core python dnsutils

# ensure nographics in server mode
log_daemon_msg "Updating nographics..." &&
  sed -i 's/setenv nographics "0"/setenv nographics "1"/g' /media/boot/boot.ini

# re-enable apt daily service
log_daemon_msg "Enable apt-daily service..." &&
  systemctl unmask apt-daily.service

# finalise
rm $0 &&
  sync &&
  reboot

