#! /bin/sh
PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

# before first boot is irrelevant
journalctl --vacuum-time=2d &&
  log_daemon_msg "Journal cleaned..."

# disable apt daily until fully bootstrapped
log_daemon_msg "Disable apt-daily service..." &&
  systemctl mask apt-daily.service

# create ssh host keys if none exits
[ ! -f /etc/ssh/ssh_host_rsa_key ] && dpkg-reconfigure openssh-server

# ensure nographics in server mode
log_daemon_msg "Updating nographics..." &&
  sed -i 's/setenv nographics "0"/setenv nographics "1"/g' /media/boot/boot.ini

# move to next stage
mv /media/boot/onboot-1 $0 &&
  sync &&
  reboot
