#! /bin/sh
PATH=/sbin:/usr/sbin:/bin:/usr/bin
export DEBIAN_FRONTEND="noninteractive"

. /lib/init/vars.sh
. /lib/lsb/init-functions

# blitz old /var
if [ -d /var.old ]; then
  log_daemon_msg "Removing /var.old..." &&
    rm -rf /var.old
fi

# clear out older journal messages
log_daemon_msg "Clearing out journal..." &&
  journalctl --vacuum-time=1d

# update the base install
log_daemon_msg "Updating base packages..." &&
  apt-get update &&
  apt-get -y upgrade

# all cluster nodes require the following packages
log_daemon_msg "Installing essential packages..." &&
  apt-get -y install lxc aufs-tools cgroup-lite apparmor docker.io \
  curl git python-is-python2 dnsutils

# re-enable apt daily service
log_daemon_msg "Enable apt-daily service..." &&
  systemctl unmask apt-daily.service

# finalise
rm $0 &&
  sync &&
  reboot
