#!/bin/bash

function ip() {
  ifconfig $1 | grep -o -e "inet addr:[0-9\.]\+" | cut -d: -f2
}

ETH0=$(ip "eth0")
DKR0=$(ip "docker0")

DKR_OPTS="-d \
  --net=host \
  --restart=unless-stopped \
  --name consul \
  -v consul:/data"

CON_OPTS="-data-dir /data \
  -bind ${ETH0} \
  -client=0.0.0.0 \
  -dc=daft"

# create a named data volume
docker volume create --name consul

if [ "$1" = "server" ]; then

  if [[ $# -eq 1 ]]; then

    # first server in the cluster
    docker run ${DKR_OPTS} -e 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}' \
      hypriot/rpi-consul:0.6.4 agent -server ${CON_OPTS} -ui -ui-dir /ui -bootstrap-expect=3

  else

    # additional server nodes
    docker run ${DKR_OPTS} -e 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}' \
      hypriot/rpi-consul:0.6.4 agent -server ${CON_OPTS} -ui -ui-dir /ui -retry-join=$2

  fi

else

  # basic client node
  docker run ${DKR_OPTS} -e 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}' \
    hypriot/rpi-consul:0.6.4 agent ${CON_OPTS} -retry-join=$2

fi

