#!/bin/bash

docker volume create --name postgres
docker run -d --restart=unless-stopped -e 'SERVICE_NAME=postgres' \
  --name postgres -p 5432:5432 -v postgres:/var/lib/postgresql/data \
  garrettheaver/armhf-postgres:9.5

