#!/bin/bash

function ip() {
  ifconfig $1 | grep -o -e "inet addr:[0-9\.]\+" | cut -d: -f2
}

ETH0=$(ip "eth0")

docker run -d \
  -h registrator \
  -v /var/run/docker.sock:/tmp/docker.sock \
  --restart=unless-stopped \
  --net=host \
  --name registrator \
  sheenhx/armhf-registrator:latest \
  -cleanup \
  -resync 300 \
  consul://${ETH0}:8500

