#! /bin/sh
PATH=/sbin:/usr/sbin:/bin:/usr/bin
export DEBIAN_FRONTEND="noninteractive"

. /lib/init/vars.sh
. /lib/lsb/init-functions

if [ -d /var.old ]; then

  # make a swap fs on the swap partition
  log_daemon_msg "Removing /var.old" &&
    rm -rf /var.old

fi

# install python for ansible
log_daemon_msg "Installing python" &&
  apt-get update &&
  apt-get -y install python

# ensure nographics in server mode
log_daemon_msg "Updating nographics" &&
  sed -i 's/setenv nographics "0"/setenv nographics "1"/g' /media/boot/boot.ini

# cleanup
rm $0 &&
  sync &&
  reboot

