#! /bin/sh
PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

# partition has been updated, resize the fs
log_daemon_msg "Resizing /" &&
  resize2fs /dev/mmcblk0p2

# setup all usb disks
for disk in `ls /dev/sd[a-z]`; do

  # setup a single partition on the disk
  log_daemon_msg "Partitioning ${disk}" &&
    printf "p\ng\nn\n1\n\n\n\n\np\nw" | fdisk ${disk} &>> /var/log/fdisk.log

  # create an xfs filesystem
  log_daemon_msg "Formatting ${disk}1" &&
    mkfs.xfs -f "${disk}1"

done

if [ -b /dev/mmcblk0p3 ]; then

  # make a swap fs on the swap partition
  log_daemon_msg "Formatting Swap" &&
    mkswap /dev/mmcblk0p3

  # set up as perm fstab entry with low swappiness
  echo "/dev/mmcblk0p3 none swap defaults 0 0" >> /etc/fstab &&
    echo 'vm.swappiness = 1' >> /etc/sysctl.conf &&
    swapon /dev/mmcblk0p3

fi

# move to stage 3
mv /media/boot/onboot3 $0 &&
  sync &&
  reboot

