#! /bin/sh
PATH=/sbin:/usr/sbin:/bin:/usr/bin
export DEBIAN_FRONTEND="noninteractive"

. /lib/init/vars.sh
. /lib/lsb/init-functions

# ntp goes weird on systemd
log_daemon_msg "Reinstalling ntp" &&
  apt-get update &&
  apt-get -y purge ntp &&
  apt-get -y install ntp

# all cluster nodes require the following packages
log_daemon_msg "Installing curl, ceph, docker, git and python" &&
  apt-get -y install curl ceph ceph-common docker git-core python

# ceph targets missing from install
log_daemon_msg "Fixing ceph targets" &&
  curl "$CEPH_REPO/ceph-mon.target" > /lib/systemd/system/ceph-mon.target &&
  systemctl enable ceph-mon.target &&
  curl "$CEPH_REPO/ceph-osd.target" > /lib/systemd/system/ceph-osd.target &&
  systemctl enable ceph-osd.target

# ensure nographics in server mode
log_daemon_msg "Updating nographics" &&
  sed -i 's/setenv nographics "0"/setenv nographics "1"/g' /media/boot/boot.ini

# cleanup
rm $0 &&
  sync &&
  reboot

