#! /bin/sh
PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

# partition has been updated, resize the fs
log_daemon_msg "Resizing /" &&
  resize2fs /dev/mmcblk0p2

if [ -b /dev/sda1 ]; then

  # create an ext4 filesystem
  log_daemon_msg "Formatting /dev/sda1" &&
    mkfs.ext4 -F /dev/sda1

  # move the /var partition on to it
  log_daemon_msg "Moving /var to /dev/sda1" &&
    mv /var /var.old &&
    mkdir /var &&
    mount /dev/sda1 /var &&
    echo "/dev/sda1 /var ext4 errors=remount-ro,noatime 0 2" >> /etc/fstab &&
    cp -dpr /var.old/* /var

fi

if [ -b /dev/mmcblk0p3 ]; then

  # make a swap fs on the swap partition
  log_daemon_msg "Formatting Swap" &&
    mkswap /dev/mmcblk0p3

  # set up swap as perm fstab entry
  echo "/dev/mmcblk0p3 none swap defaults 0 0" >> /etc/fstab &&
    swapon /dev/mmcblk0p3

fi

# move to stage 3
mv /media/boot/onboot3 $0 &&
  sync &&
  reboot

