#! /bin/sh
PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

# ok, its the very first boot, we need to resize the disk.
p2_start=`fdisk -l /dev/mmcblk0 | grep mmcblk0p2 | awk '{print $2}'`

# resize p2 as the entire disk
log_daemon_msg "Repartitioning /dev/mmcblk0..." &&
  printf "p\nd\n2\nn\np\n2\n$p2_start\n\np\nw" | fdisk /dev/mmcblk0

# create ssh host keys if none exits
[ ! -f /etc/ssh/ssh_host_rsa_key ] && dpkg-reconfigure openssh-server

# setup the hostname to match the last part of the ip
ip=`ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{print $1}' | cut -d. -f4`
log_daemon_msg "Setting hostname to punk${ip}..." &&
  echo "punk$ip" > /etc/hostname

# move to next stage
mv /media/boot/onboot-partitions $0 &&
  sync &&
  reboot

